= Acerca de Tron 0xF
:author: Marcos Cruz (programandala.net)
:revdate: 2015-11-25

// This file is part of
// Tron 0xF
// A ZX Spectrum game written in fig-Forth with Abersoft Forth

// http://programandala.net/es.programa.tron_0xf.html

// Copyright (C) 2015 Marcos Cruz (programandala.net)

// Copying and distribution of this file, with or without
// modification, are permitted in any medium without royalty
// provided the copyright notice and this notice are
// preserved.  This file is offered as-is, without any
// warranty.

// -------------------------------------------------------------

// Este fichero está escrito en formato AsciiDoc/Asciidoctor
// (http://asciidoctor.org).

== Acerca del código

Tron 0xF está escrito en Abersoft Forth (un fig-Forth 1.1 llevado a ZX
Spectrum por John Jones Steele y publicado por Melbourne House en
1983), con módulos de la biblioteca Afera (Marcos Cruz, 2015). Puedes
encontrar más detalles en
http://programandala.net/es.programa.tron_0xf.html.

== Cómo ejecutarlo

Abre el fichero <tron_0xf.szx> con tu emulador de ZX Spectrum 48K favorito.

== Cómo compilarlo

Para convertir los ficheros fuente (de código y de gráficos) en un
fichero TAP utilizable por Abersoft Forth, es preciso tener instalados
varios programas:

- Gforth: <http://gnu.org/software/gforth/>.
- bin2code: <http://metalbrain.speccy.org/link-eng.htm>.
- fsb: <http://programandala.net/en.program.fsb.html>.
- head: Componente de _GNU core utilities_.
- pbm2scr: <http://programandala.net/en.program.pbm2scr.html>.

Después entra en el directorio de Tron 0xF y ejecuta el comando
`make`.  Esto creará el fichero <tron_0xf_compiling.tap>.  Ábrelo
normalmente con tu emulador y cárgalo (con el comando de BASIC `LOAD
""` o el menú de ZX Spectrum 128). Saldrá la pantalla inicial de
Abersoft Forth.  Entonces teclea el comando `LOADT 1 LOAD`. La
compilación durará unos minutos, a la velocidad original de ZX
Spectrum. El programa se pondrá en marcha al final.

