= Pri Tron 0xF
:author: Marcos Cruz (programandala.net)
:revdate: 2020-02-14

// This file is part of
// Tron 0xF
// A ZX Spectrum game written in fig-Forth with Abersoft Forth

// http://programandala.net/eo.programo.tron_0xf.html

// Copyright (C) 2015,2016 Marcos Cruz (programandala.net)

// Copying and distribution of this file, with or without
// modification, are permitted in any medium without royalty
// provided the copyright notice and this notice are
// preserved.  This file is offered as-is, without any
// warranty.

// -------------------------------------------------------------

// Ĉi dosiero estas verkita per formato AsciiDoc/Asciidoctor
// (http://asciidoctor.org).

- link:README.adoc[English version]
- link:README.es.adoc[Versión en Español]
- link:README.ie.adoc[Version in Interlingue]

== Priskribo

Tron 0xF estas simpla Tron-stila ludo por ZX Spectrum (modelo de 48
KiB aŭ posta), de jenaj ecoj:

. 1, 2 aŭ 3 veturantoj, laŭ ajna kombino de homoj kaj robotoj.
. Konfigureblaj veturanto-koloroj.
. Konfigurablaj klavoj de homaj veturantoj.
. Se iu veturanto estas homa, veturado ekas post ajna klavpremo;
  se ĉiuj robotas, veturadoj ekas aŭtomate.
. La ludo neniam finiĝas. Se poentaro iĝas 999, ĝi rekomencas de nulo.
  Homaj veturantoj devas interkonsenti pri fin-kondiĉoj.

Lud-instrukcioj estas inkluditaj en la programo.

== Pri la kodo

Tron 0xF estas verkita en Abersoft Forth (sistemo fig-Forth 1.1
adaptita al ZX Spectrum far John Jones Steele kaj eldonita de
Melbourne House en 1983), uzante la bibliotekon Afera (Marcos Cruz,
2015). Pliaj detaloj estas en la
http://programandala.net/eo.programo.tron_0xf.html[retpaĝo de Tron
0xF].

== Kiel funkciigi

Malfermu la dosieron <tron_0xf.szx> per via plej ŝatata emulilo de ZX
Spectrum 48K.

== Kiel konstrui la programon el la fonto

Se vi volas modifi la programon, vi devas sekvi jenajn instrukciojn.
Se vi volas nur provi, rekonstrui ĝin el la nuna fonto,
vi povas iri rekte al <<pasxo2,paŝo 2>>.

=== Paŝo 1: Krei la TAP-dosieron

Por traduki la font-dosierojn de Tron 0xF en TAP-dosieron uzeblan de
Abersoft Forth, pluraj programoj devas esti instalitaj (vidu pliajn
detalojn en la dosiero link:Makefile[Makefile]):

- http://gnu.org/software/gforth/[Gforth]
- http://metalbrain.speccy.org/link-eng.htm[bin2code]
- http://programandala.net/eo.programo.fsb.html[fsb]
- head (ero de _GNU core utilities_)
- http://programandala.net/eo.programo.pbm2scr.html[pbm2scr]

Poste eniru la dosierujon de Tron 0xF kaj ordonu `make`. Tio kreos la
dosieron <tron_0xf_compiling.tap>.

[id=pasxo2]
=== Paŝo 2: Interpreti la fonton

Malfermu normale la dosieron <tron_0xf_compiling.tap> per via emulilo.
Ĝi enhavas unue Abersoft Forth, kaj poste la fontojn de la biblioteko
Afera kaj de la programo.

Enlegu Abersoft Forth per la BASIC-komando `LOAD ""` (aŭ per la menuo
de ZX Spectrum 128).  Ĉe la salutekrano de Abersoft Forth tajpu la
ordonon `LOADT 1 LOAD`.  La interpretado daŭros pli malpi 13 minutojn
je la originala rapido de ZX Spectrum.  La programo ekfunkcios je la
fino.  Tiam vi povos registri ĝin kiel sistem-kaptaĵon en ajna
formato, ekzemple SZX, SNA, Z80.

== Konataj misoj

Robotoj estas iom stultaj. Mi klopodis plurajn metodojn
pliinteligentigi ilin sen malrapidigi la ludon, sed ne atingis klaran
rezulton.

Sono estas rudimenta, kaj influas la ludo-rapidon: Dum sono aktivas,
du veturiloj pli rapidas ol tri. Por atingi decan sonon el ZX Spectrum
48 necesas verki interrompo-traktilon por ĝi.

La link:./TO-DO.adoc[lista de farendaĵoj] enhavas aliajn malgravajn
aferojn, kaj provojn pri robotaj.

La precipaj misoj estas riparotaj en onta plibonigita versio por ZX
Spectrum 128, kiu enhavas son-dediĉitan blaton, kaj
http://programandala.net/eo.programo.solo_forth.html[Solo Forth], kiu
pli rapidas ol Abersoft Forth.
