= Acerca de Tron 0xF
:author: Marcos Cruz (programandala.net)
:revdate: 2020-02-14

// This file is part of
// Tron 0xF
// A ZX Spectrum game written in fig-Forth with Abersoft Forth

// http://programandala.net/es.programa.tron_0xf.html

// Copyright (C) 2015,2016 Marcos Cruz (programandala.net)

// Copying and distribution of this file, with or without
// modification, are permitted in any medium without royalty
// provided the copyright notice and this notice are
// preserved.  This file is offered as-is, without any
// warranty.

// -------------------------------------------------------------

// Este fichero está escrito en formato AsciiDoc/Asciidoctor
// (http://asciidoctor.org).

- link:README.adoc[English version]
- link:README.eo.adoc[Esperanto-versio]
- link:README.ie.adoc[Version in Interlingue]

== Descripción

Tron 0xF es un sencillo juego de tipo Tron para ZX Spectrum (modelo de
48 KiB o posterior), con las siguientes características:

. 1, 2 o 3 pilotos, en cualquier combinación de humanos y robots.
. El color de los pilotos es configurable.
. Las teclas los pilotos humanos son configurables.
. Cuando algún participante es humano, cada carrera empieza con la
  primera pulsación de una tecla. Cuando todos los participantes son
  robots, las carreras empiezan automáticamente.
. El juego nunca termina. Cuando un marcador llega a 999, vuelve a
  empezar desde cero. Los jugadores humanos deben acordar las
  condiciones de finalización.

Las instrucciones de juego están incluidas en el programa.

== Acerca del código

Tron 0xF está escrito en Abersoft Forth (un sistema fig-Forth 1.1
llevado a ZX Spectrum por John Jones Steele y publicado por Melbourne
House en 1983), con módulos de la biblioteca Afera (Marcos Cruz,
2015). Puedes encontrar más detalles en la
http://programandala.net/es.programa.tron_0xf.html[página de Tron
0xF].

== Cómo ejecutarlo

Abre el fichero <tron_0xf.szx> con tu emulador de ZX Spectrum 48K favorito.

== Cómo crear el programa a partir de las fuentes

Si quieres modificar el programa debes seguir las siguientes instrucciones.
Si solo quieres probar a reconstruirlo a partir de las fuentes originales,
puedes ir directamente al <<paso2, paso2 >>.

=== Paso 1: Crear el fichero TAP

Para convertir los ficheros fuente (de código y de gráficos) en un
fichero TAP utilizable por Abersoft Forth, es preciso tener instalados
varios programas (véanse más detalles en el fichero
link:Makefile[Makefile]):

- http://gnu.org/software/gforth/[Gforth]
- http://metalbrain.speccy.org/link-eng.htm[bin2code]
- http://programandala.net/es.programa.fsb.html[fsb]
- head (componente de _GNU core utilities_)
- http://programandala.net/es.programa.pbm2scr.html[pbm2scr]

Después entra en el directorio de Tron 0xF y ejecuta el comando
`make`.  Esto creará el fichero <tron_0xf_compiling.tap>.

[id=paso2]
=== Paso 2: Interpretar las fuentes

Abre el fichero <tron_0xf_compiling.tap> con tu emulador de la forma
habitual. Contiene Abersoft Forth, seguido de las fuentes de la
biblioteca Afera y del programa.

Carga Abersoft Forth con el comando de BASIC `LOAD ""` (o con el menú
de ZX Spectrum 128). Saldrá la pantalla inicial de Abersoft Forth.  A
continuación teclea el comando `LOADT 1 LOAD`. La interpretación
durará unos 13 minutos, a la velocidad original de ZX Spectrum. El
programa se pondrá en marcha al final.  Entonces podrás usar tu
emulador para guardar una instantánea del sistema en cualquier
formato, por ejemplo SZX, SNA, Z80.

== Fallos conocidos

Los robots son bastante tontos. He intentado varios métodos para
hacerlos algo más listos sin ralentizar el juego pero no he obtenido
resultados claros.

El sonido es rudimentario, y afecta a la velocidad del juego: cuando
está activado, dos corredores van más rápido que tres.  Para lograr un
sonido decente en ZX Spectrum 48 habría que implementarlo con una
rutina activada por interrupciones.

La link:./TO-DO.adoc[lista de tareas pendientes] contiene algunas
otras cosas menores, y algunas pruebas hechas con los robots.

Los principales fallos serán corregidos en una futura versión mejorada
para ZX Spectrum 128, que tiene un chip específico de sonido, y
http://programandala.net/es.programa.solo_forth.html[Solo Forth], que
es más rápido y potente que Abersoft Forth.

